import { useEffect, useMemo, useState } from 'react';
import { Factory, Plus, Search, Eye, Pencil, Trash2, PackageOpen, AlertCircle } from 'lucide-react';
import { Modal } from '../../components/Modal'; import { assetService } from '../../services/api'; import type { Asset, AssetInput } from '../../types/asset'; import { AssetForm } from './components/AssetForm'; import { AssetDetails } from './components/AssetDetails'; import { StatusBadge } from './components/StatusBadge';
const typeLabels: Record<string,string>={Motor:'Motor',Pump:'Bomba',Conveyor:'Esteira',Tank:'Tanque',Robot:'Robô',Machine:'Máquina',Other:'Outro'};
type Mode = 'create'|'edit'|'view'|null;
export function AssetsPage(){
 const [assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[mode,setMode]=useState<Mode>(null),[selected,setSelected]=useState<Asset>(),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setAssets(await assetService.list());}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar ativos.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?assets.filter(a=>[a.code,a.name,a.manufacturer,a.model,a.serialNumber].some(v=>v.toLowerCase().includes(q))):assets;},[assets,query]);
 const open=(next:Exclude<Mode,null>,asset?:Asset)=>{setSelected(asset);setMode(next);setError('');};
 const submit=async(input:AssetInput)=>{setSaving(true);setError('');try{if(mode==='edit'&&selected) await assetService.update(selected.id,input);else await assetService.create(input);setMode(null);await load();}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar ativo.');}finally{setSaving(false);}};
 const remove=async(asset:Asset)=>{if(!window.confirm(`Excluir o ativo ${asset.code} — ${asset.name}? Esta ação não poderá ser desfeita.`))return;setError('');try{await assetService.remove(asset.id);setAssets(current=>current.filter(x=>x.id!==asset.id));}catch(e){setError(e instanceof Error?e.message:'Erro ao excluir ativo.');}};
 return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-800 bg-slate-950"><div className="mx-auto flex max-w-7xl items-center px-6 py-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-600 text-white"><Factory size={22}/></div><div className="ml-3"><p className="text-lg font-bold tracking-tight text-white">INDUSTRIX</p><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-400">Asset Management</p></div></div></header>
 <main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-cyan-700">Gestão de equipamentos</p><h1 className="text-3xl font-bold tracking-tight text-slate-900">Ativos Industriais</h1><p className="mt-2 text-sm text-slate-500">Cadastre, consulte e mantenha os equipamentos da sua operação.</p></div><button onClick={()=>open('create')} className="inline-flex items-center justify-center gap-2 rounded-lg bg-cyan-700 px-4 py-3 text-sm font-bold text-white shadow-sm hover:bg-cyan-800"><Plus size={18}/>Novo Ativo</button></div>
 {error&&<div className="mt-6 flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={18}/>{error}</div>}
 <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold text-slate-900">Equipamentos cadastrados</h2><p className="mt-1 text-xs text-slate-500">{filtered.length} {filtered.length===1?'ativo encontrado':'ativos encontrados'}</p></div><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-lg border border-slate-300 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-600/15" placeholder="Pesquisar código, nome, fabricante..."/></div></div>
 <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500">{['Código','Nome','Tipo','Fabricante','Modelo','Status','Ações'].map(x=><th key={x} className="whitespace-nowrap px-5 py-3.5">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={7} className="px-5 py-14 text-center text-sm text-slate-500">Carregando ativos...</td></tr>:filtered.length===0?<tr><td colSpan={7} className="px-5 py-14 text-center"><PackageOpen className="mx-auto text-slate-300" size={36}/><p className="mt-3 font-semibold text-slate-700">Nenhum ativo encontrado</p><p className="mt-1 text-sm text-slate-500">{query?'Tente ajustar os termos da pesquisa.':'Cadastre o primeiro equipamento da operação.'}</p></td></tr>:filtered.map(a=><tr key={a.id} className="text-sm hover:bg-slate-50/70"><td className="px-5 py-4 font-mono text-xs font-bold text-cyan-700">{a.code}</td><td className="px-5 py-4 font-semibold text-slate-900">{a.name}</td><td className="px-5 py-4 text-slate-600">{typeLabels[a.type]}</td><td className="px-5 py-4 text-slate-600">{a.manufacturer}</td><td className="px-5 py-4 text-slate-600">{a.model}</td><td className="px-5 py-4"><StatusBadge status={a.status}/></td><td className="px-5 py-4"><div className="flex gap-1"><button title="Visualizar" aria-label="Visualizar" onClick={()=>open('view',a)} className="rounded-md p-2 text-slate-500 hover:bg-cyan-50 hover:text-cyan-700"><Eye size={17}/></button><button title="Editar" aria-label="Editar" onClick={()=>open('edit',a)} className="rounded-md p-2 text-slate-500 hover:bg-amber-50 hover:text-amber-700"><Pencil size={17}/></button><button title="Excluir" aria-label="Excluir" onClick={()=>void remove(a)} className="rounded-md p-2 text-slate-500 hover:bg-red-50 hover:text-red-700"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div></section></main>
 {mode&&<Modal wide={mode!=='view'} title={mode==='create'?'Novo Ativo':mode==='edit'?'Editar Ativo':'Detalhes do Ativo'} subtitle={mode==='create'?'Preencha os dados do novo equipamento.':mode==='edit'?`Atualize os dados de ${selected?.code}.`:selected?.code} onClose={()=>setMode(null)}>{mode==='view'&&selected?<AssetDetails asset={selected} onClose={()=>setMode(null)}/>:<AssetForm asset={mode==='edit'?selected:undefined} loading={saving} onSubmit={submit} onCancel={()=>setMode(null)}/>}</Modal>}</div>;
}
